config/routes.rb
Mentorsapp::Application.routes.draw do
  resources :mentors
  resources :mentorshipsessions

  devise_for :users

  resources :users

  resources :mentors
  root :to  => "home#index"
  match '/home'   => 'home#index'

  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"
  get "static_pages/gallery"
  get "static_pages/resources"
  get "static_pages/connect"

  match '/help' => 'static_pages#help', :as => 'help'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact',   to: 'static_pages#contact',   via: 'get'
  match '/gallery',   to: 'static_pages#gallery',   via: 'get'
  match '/resources',   to: 'static_pages#resources',   via: 'get'
  match '/connect',   to: 'static_pages#connect',   via: 'get'
  match '/conferences', to: 'static_pages#conferences', via: 'get'
  match '/articles', to: 'static_pages#articles', via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div id="page">
  <div id="page-bgtop">
    <div id="page-bgbtm">
          <h2 class="title"><a href="#">About Us</a>          </h2>
          <p>Panama Mentors is website that will help you to start planning your career. We offer you the tools you need to succeed.
            Mentorship sessions, conferences, interesting readings, you will have all this once you are part of Panama Mentors.
            We are all once in a situation in which we wanted to get all the help we needed to guide our professional career: having someone to
            tell us more about the job industry, how to balance our strengths with our skills to choose the best career. All these resources are going
            to be provided by Panama Mentors. We will network you with professionals that will volunteer their time so you can see what they do, how they do it,
            and this will provide you with the insights of what you will like to do for your rest of your life. Start building your future with us!
          </p>
      <%= link_to 'Back to Home', root_path %>
    </div>

    <div class="post"></div>
  </div>
</div>

app/views/static_pages/articles.html.erb
<div id="page">
  <div id="page-bgtop">
    <div id="page-bgbtm">
          <h2 class="title">Articles</a></h2>
          <a href="http://money.usnews.com/money/blogs/outside-voices-careers/2010/12/06/how-to-choose-a-career-thats-best-for-you">
            How to choose your career</a>
       <p></p>
      <a href="http://mappingyourfuture.org/planyourcareer/plan.htm">
        Develop your career plan</a>

      <p></p>
      <a href="http://money.usnews.com/money/careers/articles/2012/12/18/the-best-jobs-of-2013">
        The best jobs of 2013</a>
      <p></p>
      <a href="http://careerplanning.about.com/od/careerchoicechan/tp/Career-Choice.htm">
        Making a career plan</a>
      <p></p>


      <a href="http://www.forbes.com/sites/elenabajic/2013/09/03/how-a-mentor-can-help-your-career/">
        How a mentor can help your career</a>
      <p></p


      <%= link_to 'Back to Home', root_path %>
    </div>
    <div class="post"></div>
  </div>
</div>

app/views/static_pages/conferences.html.erb
<div id="page">
  <div id="page-bgtop">
    <div id="page-bgbtm">
          <h2 class="title">Conferences</a>          </h2>
        <h4>COM Technology Conference<h4>

        <strong>Where:</strong>Sheraton Hotels, ABC Avenue
          <br></br>
        <strong>When:</strong>October 3- October 5, 2013, 8:00 a.m. - 5:00 p.m.
          <br></br>
          <strong>Guest Mentor:</strong>Steve Gates
          <br></br>
          <br></br>

           <h4>First General Mentorship Session<h4>
             <strong>Where:</strong>Sheraton Hotels, ABC Avenue
             <br></br>
             <strong>When:</strong>December 4, 2013, 8:00 a.m. - 5:00 p.m.
             <br></br>
             <strong>Guest Mentor:</strong>Steve Gates

    <%= link_to 'Back to Home', root_path %>
    </div>
    <div class="post"></div>
  </div>
</div>

app/views/static_pages/connect.html.erb
<div id="page">
  <div id="page-bgtop">
    <div id="page-bgbtm">
    <h2 class="title"><a>Connecting to a Mentor</a></h2>


  <% if user_signed_in? %>

          <%mentorsession = Mentorshipsession.find_by_user_id(current_user.id) %>

          <% if mentorsession && mentorsession.user_id == current_user.id %>
          You already have a mentor assigned.
          <br></br>
          <%= link_to "View your mentor information", mentor_path(mentorsession.mentor_id) %>


          <%else %>
                   <% Mentor.all.each do |mentor| %>
                        <% if mentor.field_study == current_user.field_study %>
                    Your assigned mentor is: <%= mentor.name %>
                    <p></p>
                    Here is the contact information:
                    <p></p>
                    Phone: <%= mentor.phone %>
                    <p></p>
                    E-mail: <%= mentor.email %>
                    <p></p>
                    <p></p>
                    <br></br>
                     <p> <strong>Create your connection if you would like to start now!</p></strong>
                    <%= link_to "Create mentorship", mentor.mentorshipsessions.create(user_id: current_user.id, field_study: current_user.field_study) %>

                                                  <p></p>

                        <%end %>
                     <%end %>
                  <ul>
                  </ul>
          <%end %>
              <% else %>

                  <p>You need to have an account to use this resource.</>
                  <p>
                  <%= link_to "Create an Account", new_user_registration_path%> or <%= link_to "Log in", new_user_session_path %>
                  </p>

    </div>
            <div class="post"></div>
          </div>
        </div>




   <% end %>
    </div>
    <div class="post"></div>
  </div>
                </div>
    </div>

app/views/static_pages/contact.html.erb
<div id="page">
  <div id="page-bgtop">
    <div id="page-bgbtm">
          <h2 class="title"><a href="#">Contact Us</a></h2>
          <p>Panama Mentors</p>
          <p>Address #123, United States</p>
          <p>Phone: 567-980-9098</p>
          <p>email: mentors@panamamentors.com</p>
<br></br>
      <%= link_to 'Back to Home', root_path %>
    </div>
    <div class="post"></div>
  </div>
</div>

app/views/static_pages/gallery.html.erb
<div id="page">
  <div id="page-bgtop">
    <div id="page-bgbtm">

          <%=image_tag "figuras/people/p_132.jpg"%>
          <%=image_tag "figuras/people/p_128.jpg"%>
          <%=image_tag "figuras/people/p_140.jpg"%>
          <%=image_tag "figuras/people/groups/gro_12.jpg"%>
          <%=image_tag "figuras/people/groups/gro_13.gif"%>
          <%=image_tag "figuras/people/groups/gro_14.gif"%>
          <%=image_tag "figuras/people/groups/gro_15.gif"%>
          <%=image_tag "figuras/people/groups/gro_16.jpg"%>
          <%=image_tag "figuras/people/p_057.jpg"%>
          <%=image_tag "figuras/people/p_061.jpg"%>
          <%=image_tag "figuras/people/p_065.jpg"%>
          <%=image_tag "figuras/people/p_023.jpg"%>

       </div>
      <div class="post"></div>
    </div>
  </div>

app/views/static_pages/help.html.erb
<div id="page">
  <div id="page-bgtop">
    <div id="page-bgbtm">
          <h2 class="title"><a href="#">Help - FAQ</a></h2>
          <p></p>
          <p><strong>1. What is Panama Mentors?</p></strong>
          <p>Panama Mentors is a program that will help you build your future career. It is designed to offer you all the tools you need to search
            and choose the most suitable program for you. You will receive assistance from a mentor, who will guide you in this process.</p>
          <p></p>
          <p><strong>2. What resources will be available for me?</p></strong>
          <p>The resources available to you include: conferences, mentorship sessions, and a lot of information. </p>
          <p></p>
          <p><strong>3. Do I need to be a student to create an account? </p></strong>
          <p>No, you don't need to be a student. The only requirement is that you wish to grow professionally.</p>
          <p></p>
          <p><strong>4. How many mentor can I network with?</p> </strong>
          <p>You can only network with one mentor at a time.</p>
      <br></br>
      <%= link_to 'Back to Home', root_path %>
    </div>
    <div class="post"></div>
  </div>
</div>

app/views/static_pages/resources.html.erb
<div id="page">
  <div id="page-bgtop">
    <div id="page-bgbtm">
          <h2 class="title"><a href="#">Resources</a></h2>



      <% if user_signed_in? %>

      <li><%= link_to "Connect to a Mentor", connect_path%></li>

          <%end  %>

      <li><%= link_to "Conferences", conferences_path%></li>
      <li><%= link_to "Articles", articles_path%></li>

      </div>
    <div class="post"></div>
  </div>
</div>