config/routes.rb
Mentorsapp::Application.routes.draw do
  resources :mentors
  resources :mentorshipsessions

  devise_for :users

  resources :users

  resources :mentors
  root :to  => "home#index"
  match '/home'   => 'home#index'

  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"
  get "static_pages/gallery"
  get "static_pages/resources"
  get "static_pages/connect"

  match '/help' => 'static_pages#help', :as => 'help'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact',   to: 'static_pages#contact',   via: 'get'
  match '/gallery',   to: 'static_pages#gallery',   via: 'get'
  match '/resources',   to: 'static_pages#resources',   via: 'get'
  match '/connect',   to: 'static_pages#connect',   via: 'get'
  match '/conferences', to: 'static_pages#conferences', via: 'get'
  match '/articles', to: 'static_pages#articles', via: 'get'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
   <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    <!--
    Design by Free CSS Templates
    http://www.freecsstemplates.org
    Released for free under a Creative Commons Attribution 2.5 License

    Name       : Escalate
    Description: A two-column, fixed-width design with dark color scheme.
    Version    : 1.0
    Released   : 20111121

    -->
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
      <meta name="keywords" content="" />
      <meta name="description" content="" />
      <meta http-equiv="content-type" content="text/html; charset=utf-8" />
      <% provide(:title, 'Home') %>
      <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600' rel='stylesheet' type='text/css'>
      <link href="style.css" rel="stylesheet" type="text/css" media="screen" />
    </head>
    <body>
    <div id="page">
      <div id="page-bgtop">
        <div id="page-bgbtm">
          <div id="content">
            <div class="post">
              <h2 class="title">Start your future here... All the resources you need to succeed</h2>
              <p class="meta">Posted by <a href="#">Susana Lau</a> on September 06, 2013
                &nbsp;&bull;&nbsp; <a href="#" class="comments"></a> &nbsp;&bull;&nbsp; <a href="#" class="permalink"></a></p>
              <div class="entry"> <a class="image "><%=image_tag "figuras/people/groups/gro_08.jpg" %></a>
                <p>When we are students finishing undergraduate studies in technology related careers or trying to find an internship as recently graduated students, it is difficult to find advice about what career paths we should follow. This website will allow students to network with professors or professionals in the technology industry and learn all the resources available to them in the job market.
                  Students will get all the tools and advices they need to build their career. Students will be able to share with a professional and have a sense of how the market works and this will provide them with the insights they need to build their career path. </p>
              </div>
            </div>
            <div class="post">
              <h2 class="title">Start your future now!</h2>
              <p class="meta">Posted by <a href="#">Susana Lau</a> on September 07, 2013
                &nbsp;&bull;&nbsp; <a class="comments"></a> &nbsp;&bull;&nbsp; <a href="#" class="permalink"></a></p>
              <div class="entry"> <a href="#" class="image"><%=image_tag "figuras/people/groups/gro_07.jpg" %> </a>
                <p>Network, participate and never stop networking. By creating an account in Panama Mentors, your doors will open to a vast amount of resources. Start here. Start today. </p>
              </div>
            </div>
            <div class="post">
              <h2 class="title">Find a mentor and start networking</a></h2>
              <p class="meta">Posted by <a href="#">Susana Lau</a> on September 07, 2013
                &nbsp;&bull;&nbsp; <a href="#" class="comments"></a> &nbsp;&bull;&nbsp; <a href="#" class="permalink"></a></p>
              <div class="entry"> <a class="image"><%=image_tag "figuras/people/groups/employee_benefits_photo.jpg"%></a>
                <p>After you create your account, update your profile. Use the "Connect to a mentor" tool to find a mentor that best matches your interests. Contact the mentor and start your career!</p>
              </div>
            </div>
            <div style="clear: both;">&nbsp;</div>
          </div>
          <!-- end #content -->
          <div id="sidebar">
            <ul>
              <li>

               <h2>Start Today!</h2>
                <ul>
                  <li><%= link_to "Create an Account", new_user_registration_path %></li>
                  <li><%= link_to "Login", new_user_session_path  %></li>
                  <li><%= link_to "Connect to a Mentor", connect_path%></li>
                </ul>
              </li>
              <li>
                <h2>Latest News</h2>
                <ul>
                  <li><%= link_to "Mentorship sessions available now!", conferences_path%></li>
                  <li><%= link_to "Technology Conference on October 3rd", conferences_path%></li>

                  </ul>
              </li>
              <li>
                <h2>Notable Mentors</h2>
                <ul>

                  <p>Steve Gates</p>
                  <p>John Smith</p>
                  <p>Mark Pelle</p>

                  <%# mentor = Mentor.find_by_name('Steve Gates') %>
                  <%#=link_to "Steve Gates", mentor_path(mentor) %>
                  <p></p>
                  <%# mentor = Mentor.find_by_name('John Smith') %>
                  <%#=link_to "John Smith", mentor_path(mentor) %>
                  <p></p>
                  <%# mentor = Mentor.find_by_name('Mark Pelle') %>
                  <%#=link_to "Mark Pelle", mentor_path(mentor) %>








                </ul>
              </li>

              <li>
                <h2>Contents</h2>
                <ul>
                    <li><%= link_to "Home", home_path%></li>
                    <li><%= link_to "About", about_path%></li>
                    <li><%= link_to "Resources", resources_path%></li>
                    <li><%= link_to "Help", help_path%></li>
                    <li><%= link_to "Gallery", gallery_path%></li>
                    <li><%= link_to "Contact Us", contact_path%></li>
                  </ul>
              </li>
            </ul>
          </div>

         </ul>
              </li>
            </ul>
          </div>
          <!-- end #sidebar -->
          <div style="clear: both;">&nbsp;</div>
        </div>
      </div>
    </div>
    <!-- end #page -->
    </div>

    </body>
    </html>























