config/routes.rb
Mentorsapp::Application.routes.draw do
  resources :mentors
  resources :mentorshipsessions

  devise_for :users

  resources :users

  resources :mentors
  root :to  => "home#index"
  match '/home'   => 'home#index'

  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"
  get "static_pages/gallery"
  get "static_pages/resources"
  get "static_pages/connect"

  match '/help' => 'static_pages#help', :as => 'help'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact',   to: 'static_pages#contact',   via: 'get'
  match '/gallery',   to: 'static_pages#gallery',   via: 'get'
  match '/resources',   to: 'static_pages#resources',   via: 'get'
  match '/connect',   to: 'static_pages#connect',   via: 'get'
  match '/conferences', to: 'static_pages#conferences', via: 'get'
  match '/articles', to: 'static_pages#articles', via: 'get'

end

app/models/mentorshipsession.rb
class Mentorshipsession < ActiveRecord::Base
  attr_accessible :mentor_id, :field_study, :user_id
  belongs_to :user
  belongs_to :mentor
  validates_uniqueness_of :user_id
  end

app/controllers/mentorshipsessions_controller.rb
class MentorshipsessionsController < ApplicationController
  # GET /mentorshipsessions
  # GET /mentorshipsessions.json
   before_filter :authorized, :only => [:edit, :update, :destroy, :new]

  def index
    @mentorshipsessions = Mentorshipsession.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mentorshipsessions }
    end
  end

  # GET /mentorshipsessions/1
  # GET /mentorshipsessions/1.json
  def show
    @mentorshipsession = Mentorshipsession.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mentorshipsession }
    end
  end

  # GET /mentorshipsessions/new
  # GET /mentorshipsessions/new.json
  def new
    @mentorshipsession = Mentorshipsession.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mentorshipsession }
    end
  end

  # GET /mentorshipsessions/1/edit
  def edit
    @mentorshipsession = Mentorshipsession.find(params[:id])
  end

  # POST /mentorshipsessions
  # POST /mentorshipsessions.json
  def create
    @mentorshipsession = Mentorshipsession.new(params[:mentorshipsession])

    respond_to do |format|
      if @mentorshipsession.save
        format.html { redirect_to @mentorshipsession, notice: 'Mentorshipsession was successfully created.' }
        format.json { render json: @mentorshipsession, status: :created, location: @mentorshipsession }
      else
        format.html { render action: "new" }
        format.json { render json: @mentorshipsession.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mentorshipsessions/1
  # PUT /mentorshipsessions/1.json
  def update
    @mentorshipsession = Mentorshipsession.find(params[:id])

    respond_to do |format|
      if @mentorshipsession.update_attributes(params[:mentorshipsession])
        format.html { redirect_to @mentorshipsession, notice: 'Mentorshipsession was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mentorshipsession.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mentorshipsessions/1
  # DELETE /mentorshipsessions/1.json
  def destroy
    @mentorshipsession = Mentorshipsession.find(params[:id])
    @mentorshipsession.destroy

    respond_to do |format|
      format.html { redirect_to mentorshipsessions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mentorshipsessions_helper.rb
module MentorshipsessionsHelper
end

app/views/mentorshipsessions/_form.html.erb
<%= form_for(@mentorshipsession) do |f| %>
  <% if @mentorshipsession.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mentorshipsession.errors.count, "error") %> prohibited this mentorshipsession from being saved:</h2>

      <ul>
      <% @mentorshipsession.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mentor_id %><br />
    <%= f.number_field :mentor_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :field_study%><br />
    <%= f.text_field :field_study %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mentorshipsessions/edit.html.erb
<h1>Editing mentorshipsession</h1>

<%= render 'form' %>

<%= link_to 'Show', @mentorshipsession %> |
<%= link_to 'Back', mentorshipsessions_path %>

app/views/mentorshipsessions/index.html.erb
<h1>Listing mentorshipsessions</h1>

<table>
  <tr>
    <th>Mentor</th>
    <th>User</th>
    <th>Field of Study</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mentorshipsessions.each do |mentorshipsession| %>
  <tr>
    <td><%= mentorshipsession.mentor_id %></td>
    <td><%= mentorshipsession.user_id %></td>
    <td><%= mentorshipsession.field_study%></td>
    <td><%= link_to 'Show', mentorshipsession %></td>

    <%if admin? %>
    <td><%= link_to 'Edit', edit_mentorshipsession_path(mentorshipsession) %></td>
    <td><%= link_to 'Destroy', mentorshipsession, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
   </tr>
<% end %>
</table>

<br />
<% if admin? %>
<%= link_to 'New Mentorshipsession', new_mentorshipsession_path %>
<% end %>

app/views/mentorshipsessions/new.html.erb
<h1>New mentorshipsession</h1>

<%= render 'form' %>

<%= link_to 'Back', mentorshipsessions_path %>

app/views/mentorshipsessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Mentor:</b>
  <%= @mentorshipsession.mentor_id %>
</p>

<p>
  <b>User:</b>
  <%= @mentorshipsession.user_id %>
</p>

<p>
  <b>Field of Study:</b>
  <%= @mentorshipsession.field_study %>
</p>

<% if admin? %>
<%= link_to 'Edit', edit_mentorshipsession_path(@mentorshipsession) %> |
<% end %>

<%= link_to 'Back', mentorshipsessions_path %>