config/routes.rb
Mentorsapp::Application.routes.draw do
  resources :mentors
  resources :mentorshipsessions

  devise_for :users

  resources :users

  resources :mentors
  root :to  => "home#index"
  match '/home'   => 'home#index'

  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"
  get "static_pages/gallery"
  get "static_pages/resources"
  get "static_pages/connect"

  match '/help' => 'static_pages#help', :as => 'help'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact',   to: 'static_pages#contact',   via: 'get'
  match '/gallery',   to: 'static_pages#gallery',   via: 'get'
  match '/resources',   to: 'static_pages#resources',   via: 'get'
  match '/connect',   to: 'static_pages#connect',   via: 'get'
  match '/conferences', to: 'static_pages#conferences', via: 'get'
  match '/articles', to: 'static_pages#articles', via: 'get'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> Panama Mentors <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "style.css", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>



<div id="wrapper">
  <div id="header-wrapper">
    <div id="header">
      <div id="logo">
        <h1><a> PANAMA MENTORS</a></h1>
        <p>Building your career path</p>
      </div>
    </div>
  </div>
  <!-- end #header -->
  <div id="menu">
    <ul>
      <li><%= link_to "Home", home_path%></li>
      <li><%= link_to "About", about_path%></li>
      <li><%= link_to "Resources", resources_path%></li>
      <li><%= link_to "Help", help_path%></li>
      <li><%= link_to "Gallery", gallery_path%></li>
      <li><%= link_to "Contact Us", contact_path%></li>
    </ul>
  </div>

  <div id="page">
    <div id="page-bgtop">
      <div id="page-bgbtm">
        <div id="user_nav">
          <% if user_signed_in? %>

              <h3>You are signed in as</h3>
              <% mentorsession = Mentorshipsession.find_by_user_id(current_user.id) %>

              <%= current_user.firstname %>   <%= current_user.lastname%>
              <br></br>
              <%=link_to "My account", user_path(current_user) %>   ||
              <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
              <% if mentorsession && mentorsession.user_id == current_user.id %>  ||
              <%= link_to "My mentor", mentor_path(mentorsession.mentor_id) %>
                  <%end %>

        <% end %>
        </div>
        <div class="post"></div>
      </div>
    </div>


    <%= yield %>



    <div id="footer">
      <p>Copyright (c) 2013 Panama Mentors. All rights reserved. | Photos by <a href="http://www.cbtrends.com/free-downloads.html/">CBTrends</a> | Design by <a href="http://www.freecsstemplates.org/" rel="nofollow">FreeCSSTemplates.org</a>.</p>
    </div>


</body>
</html>